default_stages: [commit]
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: forbid-submodules

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: python
        language_version: python3.11
        types: [ python ]
        require_serial: true
        entry: .venv/bin/ruff
  #     - id: mypy
  #       name: mypy
  #       entry: .venv/bin/mypy
  #       language: python
  #       language_version: python3.11
  #       types: [python]
  #       require_serial: true
  #       additional_dependencies: []
  #       args:
  #         - --show-error-codes
  #         - --ignore-missing-imports
  #         - --disallow-untyped-defs

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
